sudo apt install python-pip
sudo apt install python-gtk2
sudo pip install xlrd
sudo pip install xlwt
sudo pip install sh
sudo pip install reportlab
sudo apt-get install ttf-mscorefonts-installer
sudo apt install python-serial
sudo pip install urllib3